config/routes.rb
Rails.application.routes.draw do
  devise_for :staffs
  devise_for :admins_paynow

  root 'home#index'

  resources :companies do
    get 'my_staff', on: :member
    post 'reset_token'
    put 'request_suspension', on: :member
  end

  namespace :company do
    resources :products, only: %i[index show new create edit update destroy]
    resources :charges, only: %i[index update] do
      get 'new_reject'
      get 'new_approve'
    end
  end

  resources :payment_methods
  
  resources :receipts, only: %i[show]

  namespace :staff do
    put 'block_staff'
    resources :payment_methods, only: %i[index show] do
      resources :boletos, only: %i[new create edit update destroy]
      resources :pixes, only: %i[new create edit update destroy]
      resources :credit_cards, only: %i[new create edit update destroy]
    end
  end

  namespace :api do
    namespace :v1 do
      resources :customers, only: %i[index create]
      resources :charges, only: %i[create] do
        get 'search', on: :collection
      end
    end
  end

end

app/models/payment_method.rb
class PaymentMethod < ApplicationRecord
  enum pay_type: { boleto: 0, credit_card: 1, pix: 2 }
  has_many :boletos, dependent: :destroy
  has_many :pixes, dependent: :destroy
  has_many :credit_cards, dependent: :destroy
  has_many :companies, through: :boletos
  has_many :companies, through: :pixes
  has_many :companies, through: :credit_cards
  has_one_attached :icon
  validates :name, :charging_fee, :maximum_charge,
            :pay_type, presence: { message: 'não pode ficar em branco' }
end

app/controllers/payment_methods_controller.rb
class PaymentMethodsController < ApplicationController
  before_action :authenticate_admin_paynow!
  def index
    @payment_methods = PaymentMethod.all
  end

  def show
    @payment_method = PaymentMethod.find(params[:id])
  end

  def new
    @payment_method = PaymentMethod.new
  end

  def create
    @payment_method = PaymentMethod.new(payment_method_params)
    return render :new unless @payment_method.save

    redirect_to payment_methods_path
  end

  def edit
    @payment_method = PaymentMethod.find(params[:id])
  end

  def update
    @payment_method = PaymentMethod.find(params[:id])
    return render :edit unless @payment_method.update(payment_method_params)

    redirect_to @payment_method, notice: 'Meio de pagamento editado com sucesso'
  end

  def destroy
    @payment_method = PaymentMethod.find(params[:id])
    @payment_method.destroy
    redirect_to payment_methods_path, notice: 'Meio de pagamento apagado com sucesso'
  end

  private

  def payment_method_params
    params
      .require(:payment_method)
      .permit(:name, :charging_fee, :maximum_charge, :pay_type, :icon)
  end
end

app/controllers/staff/payment_methods_controller.rb
class Staff::PaymentMethodsController < ApplicationController
  before_action :authenticate_staff!
  before_action :set_payment_method, only: %i[show]

  def index
    @payment_methods = PaymentMethod.all
  end

  def show; end

  private

  def set_payment_method
    @payment_method = PaymentMethod.find(params[:id])
  end
end

app/views/payment_methods/_form.html.erb
<% if payment_method.errors.any? %>
  <p>Foram encontrados <%= payment_method.errors.count %> erro(s):</p>
  <ul>
    <% payment_method.errors.full_messages.each do |error|%>
      <li><%= error %></li>
    <% end %>
  </ul>
<% end %>
<%= form_with model: payment_method do |f| %>
  <%= f.label :name, 'Nome'%>
  <%= f.text_field :name %>
  <%= f.label :icon, 'Ícone' %>
  <%= f.file_field :icon %>
  <%= f.label :charging_fee, 'Taxa de cobrança'%>
  <%= f.number_field :charging_fee %>
  <%= f.label :maximum_charge, 'Cobrança máxima'%>
  <%= f.number_field :maximum_charge %>
  <%= f.label :pay_type, 'Tipo' %>
  <%= f.select :pay_type,  PaymentMethod.pay_types.keys.collect { |pay_type| [PaymentMethod.human_enum_name(:pay_type, pay_type), pay_type] } %>
  <%= f.submit button_text %>
<% end %>

app/views/payment_methods/edit.html.erb
<h1>Editar meio de pagamento</h1>
<%= render 'form', payment_method: @payment_method, button_text: 'Salvar' %>
<%= link_to 'Voltar', payment_methods_path %>

app/views/payment_methods/index.html.erb
<%= flash[:notice] %>
<% unless @payment_methods.empty?%>
  <% @payment_methods.each do |method|%>
    <h2><%= image_tag method.icon %> <%=link_to method.name, method %></h2>
    <ul><%= number_to_percentage method.charging_fee, precision:2, significant: true, separator: ',', delimiter:'.' %></ul>
    <ul><%= number_to_currency method.maximum_charge,unit:'R$ ',separator:',',delimiter:'.' %></ul>
    <ul>Tipo <%= PaymentMethod.human_enum_name(:pay_type, method.pay_type.to_sym) %> </ul>
  <% end %>
<% else%>
  <p>Nenhum meio de pagamento cadastrado</p>
<% end %>
<%= link_to 'Voltar', root_path %>
<%= link_to 'Cadastrar meio de pagamento', new_payment_method_path %>

app/views/payment_methods/new.html.erb
<h1>Cadastrar meio de pagamento</h1>
<%= render 'form', payment_method: @payment_method, button_text: 'Enviar' %>

app/views/payment_methods/show.html.erb
<h1><%= image_tag @payment_method.icon %> <%= @payment_method.name %></h1>
<dl>
  <dt>Taxa de cobrança</dt>
  <dd><%= number_to_percentage @payment_method.charging_fee, precision:2, significant: true, separator: ',', delimiter:'.' %></dd>
  <dt>Taxa máxima cobrável</dt>
  <dd><%= number_to_currency @payment_method.maximum_charge,unit:'R$ ',separator:',',delimiter:'.' %></dd>
  <dt>Tipo <%= PaymentMethod.human_enum_name(:pay_type, @payment_method.pay_type.to_sym) %></dd>
</dl>
<%= link_to 'Voltar', payment_methods_path %>
<%= link_to 'Editar', edit_payment_method_path(@payment_method) %>
<%= link_to 'Apagar', payment_method_path(@payment_method),method: :delete, data:{confirm: 'Você realmente deseja apagar este meio de pagamento?'} %>