config/routes.rb
Rails.application.routes.draw do
  devise_for :staffs
  devise_for :admins_paynow

  root 'home#index'

  resources :companies do
    get 'my_staff', on: :member
    post 'reset_token'
    put 'request_suspension', on: :member
  end

  namespace :company do
    resources :products, only: %i[index show new create edit update destroy]
    resources :charges, only: %i[index update] do
      get 'new_reject'
      get 'new_approve'
    end
  end

  resources :payment_methods
  
  resources :receipts, only: %i[show]

  namespace :staff do
    put 'block_staff'
    resources :payment_methods, only: %i[index show] do
      resources :boletos, only: %i[new create edit update destroy]
      resources :pixes, only: %i[new create edit update destroy]
      resources :credit_cards, only: %i[new create edit update destroy]
    end
  end

  namespace :api do
    namespace :v1 do
      resources :customers, only: %i[index create]
      resources :charges, only: %i[create] do
        get 'search', on: :collection
      end
    end
  end

end

app/models/payment_method.rb
class PaymentMethod < ApplicationRecord
  enum pay_type: { boleto: 0, credit_card: 1, pix: 2 }
  has_many :boletos, dependent: :destroy
  has_many :pixes, dependent: :destroy
  has_many :credit_cards, dependent: :destroy
  has_many :companies, through: :boletos
  has_many :companies, through: :pixes
  has_many :companies, through: :credit_cards
  has_one_attached :icon
  validates :name, :charging_fee, :maximum_charge,
            :pay_type, presence: { message: 'não pode ficar em branco' }
end

app/models/staff.rb
class Staff < ApplicationRecord
  belongs_to :company, optional: true
  before_create :associate_company
  validates :email, email: true
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  def associate_company
    comp = find_company
    self.company = comp
    self.token = comp.token unless comp.nil?
  end

  def find_company
    companies = Company.all
    cmp = companies.select do |c|
      c.email[/@(.)*$/] == email[/@(.)*$/]
    end
    cmp.first
  end

  def active_for_authentication?
    super && staff_active
  end

  def allowed_on?(other_company)
    company == other_company && admin?
  end

  def inactive_message
    'Esta conta foi bloqueada pelo administrador'
  end

  def staff_status
    return 'Ativo' if staff_active?

    'Bloqueado'
  end

  def staff_permission
    return 'Administrador' if admin?

    'Comum'
  end
end

app/controllers/payment_methods_controller.rb
class PaymentMethodsController < ApplicationController
  before_action :authenticate_admin_paynow!
  def index
    @payment_methods = PaymentMethod.all
  end

  def show
    @payment_method = PaymentMethod.find(params[:id])
  end

  def new
    @payment_method = PaymentMethod.new
  end

  def create
    @payment_method = PaymentMethod.new(payment_method_params)
    return render :new unless @payment_method.save

    redirect_to payment_methods_path
  end

  def edit
    @payment_method = PaymentMethod.find(params[:id])
  end

  def update
    @payment_method = PaymentMethod.find(params[:id])
    return render :edit unless @payment_method.update(payment_method_params)

    redirect_to @payment_method, notice: 'Meio de pagamento editado com sucesso'
  end

  def destroy
    @payment_method = PaymentMethod.find(params[:id])
    @payment_method.destroy
    redirect_to payment_methods_path, notice: 'Meio de pagamento apagado com sucesso'
  end

  private

  def payment_method_params
    params
      .require(:payment_method)
      .permit(:name, :charging_fee, :maximum_charge, :pay_type, :icon)
  end
end

app/controllers/staff/boletos_controller.rb
class Staff::BoletosController < ApplicationController
  before_action :authenticate_staff!
  before_action :set_payment_method, only: %i[new create edit update destroy]
  before_action :set_company, only: %i[new create]
  before_action :set_boleto, only: %i[edit update destroy]

  def new
    return redirect_to [:staff, @payment_method] if boleto_exists

    @boleto = Boleto.new
  end

  def create
    @boleto = Boleto.new(boleto_params)
    @boleto.payment_method = @payment_method
    @boleto.company = @company
    return render :new, error: 'Não foi possível fazer configuração' unless @boleto.save!

    redirect_to [:staff, @payment_method], notice: 'Meio de pagamento configurado com sucesso'
  end

  def edit; end

  def update
    return render :edit, error: 'Não foi possível atualizar configuração' unless @boleto.update(boleto_params)

    redirect_to [:staff, @payment_method], notice: 'Configuração de meio de pagamento editada com sucesso'
  end

  def destroy
    @boleto.destroy
    redirect_to [:staff, @payment_method], notice: 'Meio de pagamento desabilitado com sucesso'
  end

  private

  def boleto_params
    params
      .require(:boleto)
      .permit(:bank_code, :agency, :account)
  end

  def set_boleto
    @boleto = Boleto.find(params[:id])
  end

  def set_company
    @company = Company.find(current_staff[:company_id])
  end

  def set_payment_method
    @payment_method = PaymentMethod.find(params[:payment_method_id])
  end

  def boleto_exists
    return true if @payment_method.boletos.find { |boleto| boleto.company == @company }

    false
  end
end

app/controllers/staff/credit_cards_controller.rb
class Staff::CreditCardsController < ApplicationController
  before_action :authenticate_staff!
  before_action :set_payment_method, only: %i[new create edit update destroy]
  before_action :set_company, only: %i[new create]
  before_action :set_credit_card, only: %i[edit update destroy]

  def new
    return redirect_to [:staff, @payment_method] if credit_card_exists

    @credit_card = CreditCard.new
  end

  def create
    @credit_card = CreditCard.new(credit_card_params)
    @credit_card.payment_method = @payment_method
    @credit_card.company = @company
    return render :new, error: 'Não foi possível fazer configuração' unless @credit_card.save!

    redirect_to [:staff, @payment_method], notice: 'Meio de pagamento configurado com sucesso'
  end

  def edit; end

  def update
    unless @credit_card.update(credit_card_params)
      return render :edit,
                    error: 'Não foi possível atualizar configuração'
    end

    redirect_to [:staff, @payment_method], notice: 'Configuração de meio de pagamento editada com sucesso'
  end

  def destroy
    @credit_card.destroy
    redirect_to [:staff, @payment_method], notice: 'Meio de pagamento desabilitado com sucesso'
  end

  private

  def credit_card_params
    params
      .require(:credit_card)
      .permit(:cc_code)
  end

  def set_credit_card
    @credit_card = CreditCard.find(params[:id])
  end

  def set_company
    @company = Company.find(current_staff[:company_id])
  end

  def set_payment_method
    @payment_method = PaymentMethod.find(params[:payment_method_id])
  end

  def credit_card_exists
    return true if @payment_method.credit_cards.find { |credit_card| credit_card.company == @company }

    false
  end
end

app/controllers/staff/payment_methods_controller.rb
class Staff::PaymentMethodsController < ApplicationController
  before_action :authenticate_staff!
  before_action :set_payment_method, only: %i[show]

  def index
    @payment_methods = PaymentMethod.all
  end

  def show; end

  private

  def set_payment_method
    @payment_method = PaymentMethod.find(params[:id])
  end
end

app/controllers/staff/pixes_controller.rb
class Staff::PixesController < ApplicationController
  before_action :authenticate_staff!
  before_action :set_payment_method, only: %i[new create edit update destroy]
  before_action :set_company, only: %i[new create]
  before_action :set_pix, only: %i[edit update destroy]

  def new
    return redirect_to [:staff, @payment_method] if pix_exists

    @pix = Pix.new
  end

  def create
    @pix = Pix.new(pix_params)
    @pix.payment_method = @payment_method
    @pix.company = @company
    return render :new, error: 'Não foi possível fazer configuração' unless @pix.save!

    redirect_to [:staff, @payment_method], notice: 'Meio de pagamento configurado com sucesso'
  end

  def edit; end

  def update
    return render :edit, error: 'Não foi possível atualizar configuração' unless @pix.update(pix_params)

    redirect_to [:staff, @payment_method], notice: 'Configuração de meio de pagamento editada com sucesso'
  end

  def destroy
    @pix.destroy
    redirect_to [:staff, @payment_method], notice: 'Meio de pagamento desabilitado com sucesso'
  end

  private

  def pix_params
    params
      .require(:pix)
      .permit(:pix_key, :bank_code)
  end

  def set_pix
    @pix = Pix.find(params[:id])
  end

  def set_company
    @company = Company.find(current_staff[:company_id])
  end

  def set_payment_method
    @payment_method = PaymentMethod.find(params[:payment_method_id])
  end

  def pix_exists
    return true if @payment_method.pixes.find { |pix| pix.company == @company }

    false
  end
end

app/controllers/staff/staff_controller.rb
class Staff::StaffController < ActionController::Base
  before_action :set_staff_to_block, only: %i[block_staff]

  def block_staff
    if validate_admin_staff
      @staff_to_block.staff_active = false
      @staff_to_block.save
    else
      alert: 'Você não pode bloquear este funcionário'
    end
  end

  private
  def validate_admin_staff
    current_staff.admin? && current_staff.company == @staff_to_block.company
  end

  def set_staff_to_block
    @staff_to_block = Staff.find(params[:id])
  end
end

app/controllers/staff_controller.rb
class StaffController < ApplicationController
  before_action :set_staff_to_block, only: %i[block_staff]

  def block_staff
    if validate_admin_staff
      @staff_to_block.staff_active = false
      @staff_to_block.save
      redirect_to my_staff_company_path(current_staff.company)
    else
      flash[:alert] = 'Você não pode bloquear este funcionário'
    end
  end

  def validate_admin_staff
    current_staff.admin? && current_staff.company == @staff_to_block.company
  end

  def set_staff_to_block
    @staff_to_block = Staff.find(params[:format])
  end
end

app/views/staff/payment_methods/_config.html.erb
<% case payment_method.pay_type %>
  <% when 'boleto' %>
    <% boleto = payment_method.boletos.find{|boleto| boleto.company == current_staff.company}%>
    <% if boleto %>
      <h3>Configuração</h3>
      <dl>
        <dt>Código do banco</dt>
        <dd><%= boleto.bank_code %></dd>
        <dt>Agência</dt>
        <dd><%= boleto.agency %></dd>
        <dt>Conta</dt>
        <dd><%= boleto.account %></dd>
      </dl>
      <%=  link_to 'Editar', edit_staff_payment_method_boleto_path(payment_method,boleto) %>
      <%=  link_to 'Desabilitar', staff_payment_method_boleto_path(payment_method,boleto),method: :delete, data:{confirm: 'Você realmente deseja desabilitar este método de pagamento?'} %>
    <% else %>
      <%= link_to 'Configurar', new_staff_payment_method_boleto_path(payment_method) %>
    <% end %>
  <% when 'pix' %>
    <%  credit_card = payment_method.pixes.find{| credit_card| credit_card.company == current_staff.company}%>
    <% if  credit_card %>
      <h3>Configuração</h3>
      <dl>
        <dt>Chave PIX</dt>
        <dd><%=  credit_card.pix_key %></dd>
        <dt>Código do banco</dt>
        <dd><%=  credit_card.bank_code %></dd>
      </dl>
      <%=  link_to 'Editar', [:edit,:staff,payment_method, credit_card] %>
      <%=  link_to 'Desabilitar', [:staff,payment_method, credit_card], method: :delete, data:{confirm: 'Você realmente deseja desabilitar este método de pagamento?'} %>
    <% else %>
      <%= link_to 'Configurar', new_staff_payment_method_pix_path(payment_method) %>
    <% end %>
  <% when 'credit_card' %>
    <%  credit_card = payment_method.credit_cards.find{|credit_card|  credit_card.company == current_staff.company}%>
    <% if  credit_card %>
      <h3>Configuração</h3>
      <dl>
        <dt>Conta junto à operadora de cartão</dt>
        <dd><%=  credit_card.cc_code %></dd>
      </dl>
      <%=  link_to 'Editar', [:edit,:staff,payment_method, credit_card] %>
      <%=  link_to 'Desabilitar', [:staff,payment_method, credit_card], method: :delete, data:{confirm: 'Você realmente deseja desabilitar este método de pagamento?'} %>
    <% else %>
      <%= link_to 'Configurar', [:new,:staff,payment_method,:credit_card] %> 
    <% end %>
  <% else %>
    <p>Opção de meio de pagamento inválida</p>
<% end %>

app/views/staff/payment_methods/index.html.erb
<%= flash[:notice] %>
<% unless @payment_methods.empty?%>
  <% @payment_methods.each do |method|%>
    <h2><%= image_tag method.icon %> <%=link_to method.name, staff_payment_method_path(method) %></h2>
    <ul><%= number_to_percentage method.charging_fee, precision:2, significant: true, separator: ',', delimiter:'.' %></ul>
    <ul><%= number_to_currency method.maximum_charge,unit:'R$ ',separator:',',delimiter:'.' %></ul>
    <ul>Tipo <%= PaymentMethod.human_enum_name(:pay_type, method.pay_type.to_sym) %></ul>
  <% end %>
<% else%>
  <p>Nenhum meio de pagamento cadastrado</p>
<% end %>
<%= link_to 'Voltar', root_path %>

app/views/staff/payment_methods/show.html.erb
<%= flash[:notice] %>
<h1><%= image_tag @payment_method.icon %> <%= @payment_method.name %></h1>
<dl>
  <dt>Taxa de cobrança</dt>
  <dd><%= number_to_percentage @payment_method.charging_fee, precision:2, significant: true, separator: ',', delimiter:'.' %></dd>
  <dt>Taxa máxima cobrável</dt>
  <dd><%= number_to_currency @payment_method.maximum_charge,unit:'R$ ',separator:',',delimiter:'.' %></dd>
  <dt>Tipo <%= PaymentMethod.human_enum_name(:pay_type, @payment_method.pay_type.to_sym) %> </dd>
</dl>

<%= render 'config', payment_method: @payment_method %>