config/routes.rb
Rails.application.routes.draw do
  devise_for :staffs
  devise_for :admins_paynow

  root 'home#index'

  resources :companies do
    get 'my_staff', on: :member
    post 'reset_token'
    put 'request_suspension', on: :member
  end

  namespace :company do
    resources :products, only: %i[index show new create edit update destroy]
    resources :charges, only: %i[index update] do
      get 'new_reject'
      get 'new_approve'
    end
  end

  resources :payment_methods
  
  resources :receipts, only: %i[show]

  namespace :staff do
    put 'block_staff'
    resources :payment_methods, only: %i[index show] do
      resources :boletos, only: %i[new create edit update destroy]
      resources :pixes, only: %i[new create edit update destroy]
      resources :credit_cards, only: %i[new create edit update destroy]
    end
  end

  namespace :api do
    namespace :v1 do
      resources :customers, only: %i[index create]
      resources :charges, only: %i[create] do
        get 'search', on: :collection
      end
    end
  end

end

app/models/company.rb
class Company < ApplicationRecord
  has_many :boletos, dependent: :destroy
  has_many :credit_cards, dependent: :destroy
  has_many :customers, through: :customer_tokens
  has_many :customer_tokens, dependent: :restrict_with_error
  has_many :payment_methods, through: :boletos
  has_many :payment_methods, through: :credit_cards
  has_many :payment_methods, through: :pixes
  has_many :pixes, dependent: :destroy
  has_many :products, dependent: :destroy
  has_many :staffs, dependent: :destroy
  validates :email, email: true

  def destroy_allowed?(user)
    suspension_required? && !suspension_required_by.eql?(user)
  end

  def requested_suspension_message
    "Suspensão da empresa #{corporate_name} (Token: #{token}) solicitada"
  end

  def suspension_required_by
    Staff.find suspension_required_by_id
  end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :authenticate_staff!, only: %i[new create show]
  before_action :authenticate_admin_paynow!, only: %i[index request_suspension]

  def index
    @companies = Company.all
  end

  def new
    @company = Company.new
  end

  def create
    @company = Company.new(company_params)
    @staff_adm = current_staff
    return render :new unless @company.save

    set_new_token
    redirect_to @company, notice: 'Empresa criada com sucesso'
  end

  def show
    @company = Company.find(params[:id])
  end

  def reset_token
    @staff = current_staff
    @company = Company.find(params[:company_id])
    return permission_denied(@company) unless @staff&.allowed_on? @company

    set_new_token
    redirect_to @company, notice: 'Token resetado com sucesso!'
  end

  def my_staff
    @company = Company.find(params[:id])
    return permission_denied(root_path) unless current_staff&.allowed_on? @company

    @staffs = @company.staffs.all
  end

  def request_suspension
    @company = Company.find(params[:id])
    update_suspension_required
    redirect_to companies_path, notice: 'Suspensão solicitada com sucesso'
  end

  def destroy
    @company = Company.find(params[:id])
    permission_denied(companies_path) unless @company&.destroy_allowed? current_admin_paynow

    @company.destroy
    redirect_to companies_path, notice: 'Empresa desligada'
  end

  private

  def company_params
    params
      .require(:company)
      .permit(:corporate_name, :email, :cnpj, :address)
  end

  def generate_token
    charset = Array('A'..'Z') + Array('a'..'z') + Array('0'..'9')
    Array.new(20) { charset.sample }.join
  end

  def permission_denied(path)
    redirect_to path, alert: 'Permissão negada'
  end

  def set_adm
    @staff_adm&.update!(set_adm_hash)
  end

  def set_adm_hash
    {
      token: @company.token,
      admin: true,
      company: @company
    }
  end

  def set_new_token
    @company.token = generate_token
    set_adm
    set_staffs
    @company.save!
  end

  def set_staffs
    @company.staffs.each { |staff| staff.update! token: @company.token }
  end

  def update_suspension_required_hash
    {
      suspension_required: true,
      suspension_required_by_id: current_admin_paynow.id
    }
  end

  def update_suspension_required
    @company.update!(**update_suspension_required_hash)
  end
end

app/controllers/company/charges_controller.rb
class Company::ChargesController < ApplicationController
  before_action :set_company, only: %i[index]
  def index
    token = @company.token
    @charges = Charge.where(company_token: token)
  end

  def update
    @charge = Charge.find(params[:id])
    @charge.status = params[:charge][:status]
    @charge.history = if @charge.history.nil?
                        params_history
                      else
                        "#{@charge.history}\n\n#{params_history}"
                      end
    @charge.save
    redirect_to company_charges_path
  end

  def new_reject
    @charge = Charge.find(params[:charge_id])
  end

  def new_approve
    @charge = Charge.find(params[:charge_id])
    @charge.status = 'aprovada'
    @charge
  end

  private

  def set_company
    @company = current_staff.company
  end

  def params_history
    if params[:charge][:status].eql?('aprovada')
      "Aprovada em #{params[:charge][:approved_date]}"
    else
      "Data da tentativa de pagamento: #{params[:charge][:denied_date]}\n"\
        "Código de retorno: #{params[:charge][:return_code]}"
    end
  end
end

app/controllers/company/products_controller.rb
class Company::ProductsController < ApplicationController
  before_action :authenticate_staff!
  before_action :auth_staff_company!, only: %i[show edit update destroy]
  before_action :set_company, only: %i[index show new create edit update destroy]
  before_action :set_product, only: %i[show edit update destroy]

  def index
    flash[:alert] = 'Permissão negada' unless permit_company
    @products = @company.products.all
  end

  def show; end

  def new
    return redirect_to [@company, :products], alert: 'Permissão negada' unless permit_company

    @product = @company.products.new
  end

  def create
    @product = @company.products.new(product_params)
    return render :new, alert: 'Erros foram encontrados' unless @product.save

    redirect_to [@company, @product], notice: 'Produto cadastrado com sucesso'
  end

  def edit; end

  def update
    return render :edit, alert: 'Erros foram encontrados' unless @product.update(product_params)

    redirect_to [@company, @product], notice: 'Produto editado com sucesso'
  end

  def destroy
    @product.destroy
    redirect_to [@company, :products], notice: 'Produto apagado com sucesso'
  end

  private

  def permit_company
    comp = Company.find(params[:format])
    set_company
    return true if comp == @company

    false
  end

  def auth_staff_company!
    set_product
    set_company
    return true if @product.company == @company

    redirect_to [@company, :products], alert: 'Permissão negada'
  end

  def set_company
    @company = current_staff.company
  end

  def set_product
    @product = Product.find(params[:id])
  end

  def product_params
    params
      .require(:product)
      .permit(:name, :price, :sale_discount)
  end
end

app/views/companies/_form.html.erb
<% if company.errors.any? %>
  <p>Foram encontrados <%= company.errors.count %> erro(s):</p>
  <ul>
    <% company.errors.full_messages.each do |error|%>
      <li><%= error %></li>
    <% end %>
  </ul>
<% end %>
<%= form_with model: company do |f| %>
  <%= f.label :corporate_name, 'Razão social'%>
  <%= f.text_field :corporate_name %>
  <%= f.label :address, 'Endereço' %>
  <%= f.text_field :address %>
  <%= f.label :email, 'Email'%>
  <%= f.text_field :email %>
  <%= f.label :cnpj, 'CNPJ'%>
  <%= f.text_field :cnpj %>
  <%= f.submit button_text %>
<% end %>

app/views/companies/index.html.erb
<%= flash[:notice] %>
<%= flash[:alert] %>
<h1>Empresas Cadastradas</h1>
<% unless @companies.empty?%>
  <% @companies.each do |company|%>
    <div class='company' id=<%="#{company.id}"%>>
      <h2><%= company.corporate_name %></h1>
      <ul>Token: <%= company.token %></ul>
      <ul><%= company.email %></ul>
      <ul><%= company.cnpj %></ul>
      <ul><%= company.address %></ul>
      <% if company.suspension_required %>
        <ul><%= company.requested_suspension_message %></ul>
        <ul><%= link_to 'Confirmar suspensão', company_path(company), method: :delete unless company.suspension_required_by_id == current_admin_paynow.id %></ul>
      <% else %>
      <ul><%= link_to 'Solicitar suspensão', request_suspension_company_path(company), method: :put %></ul>
      <% end %>
      
    </div>
  <% end %>
<% else%>
  <p>Nenhuma empresa cadastrada</p>
<% end %>
<%= link_to 'Voltar', root_path %>

app/views/companies/my_staff.html.erb
<%= flash[:notice] %>
<%= flash[:alert] %>
<h1>Funcionários da empresa <%= current_staff.company.corporate_name %></h1>
<% unless @staffs.empty?%>
  <% @staffs.each do |staff|%>
    <div class = staff<%= staff.id %>>
      <p><%= staff.email %> Status: <%= staff.staff_status  %> Permissão: <%= staff.staff_permission %> </p>
      <%= link_to 'Bloquear acesso', staff_block_staff_path(staff), method: :put unless staff.admin? || !staff.staff_active? %>
    </div>
  <% end %>
<% else%>
  <p>Nenhum funcionário, contatar representante PayNow</p>
<% end %>
<%= link_to 'Voltar', company_path(current_staff.company) %>

app/views/companies/new.html.erb
<h1>Cadastre sua empresa</h1>
<%= render 'form', company: @company, button_text: 'Cadastrar empresa' %>

app/views/companies/show.html.erb
<h1><%= @company.corporate_name %></h1>
<p>Token: <%= @company.token %></p>
<dl>
  <dt>Email</dt>
  <dd><%= @company.email %></dd>
  <dt>CNPJ</dt>
  <dd><%= @company.cnpj %></dd>
  <dt>Endereço</dt>
  <dd><%= @company.address %></dd>
</dl>
<%= link_to 'Resetar token da empresa', company_reset_token_path(@company), method: :post if current_staff.admin? %>
<%= link_to 'Cobranças', company_charges_path if current_staff.admin? %>
<%= link_to 'Produtos', company_products_path(@company) %>
<%= link_to 'Funcionários', my_staff_company_path(@company) if current_staff.admin? %>
<%= link_to 'Voltar', root_path %>
<%= link_to 'Editar', edit_company_path(@company) %>